#!/bin/sh
NAME=""
EXT=md
FMT=markdown
LC_ALL=en_US.UTF-8
PATH=/bin:/usr/bin:/usr/local/bin
PREFIX="/"
FOOTER=""
export LC_ALL PATH

menu() {
	for i in `ls -F $1 | grep -v index.$EXT | sort`
	do
		case $i in
		*.$EXT)
			base=`echo $i | sed "s/.\$EXT$//"`
			cleanbase=`echo $base | sed 's/_/ /g'`
			if test "x$base" = "x$2"
			then
				echo "<li class='current'><a href='$base.html'>$cleanbase</a></li>"
			else
				echo "<li><a href='$base.html'>$cleanbase</a></li>"
			fi
			cur=1
			;;
		*/)
			echo "<li><a href='$i'>$i</a></li>"
			;;
		esac
	done
	cat <<END
		<li>&nbsp;</li>
	</ul>
		</div>
END
}

page() {
	mtime=`ls -l --time-style=long-iso $1$2.$EXT | awk '{ print $6 }'`
	title=`echo $4 | sed 's/.html//'`
	cat <<END
<!DOCTYPE HTML>
<html>
<head>
	<meta charset="utf-8">
	<title>$title</title>
	<!-- <link type="text/css" rel="stylesheet" href="/style.css"> -->
	<link type="text/css" rel="stylesheet" href="${PREFIX}style.css"> 
</head>
<body>
<div id="container">
	<div id="main">
		<div id="path">$3</a></div>
		<div id="menu">
		<ul>
END
	menu $1 $2
cat <<END
		<div id="content">
END

        $FMT $1$2.$EXT
	cat <<END
		</div>
	</div>
	<div id="footer">
		$FOOTER &nbsp;&middot;&nbsp <a href="http://validator.w3.org/check?uri=referer">Validate</a> &nbsp;&middot;&nbsp; generated: $mtime
	</div>
</div>
</body></html>
END
}

process() {
	for i in `ls -F $1`
	do
		case $i in
		*.$EXT)
			echo processing $1$i
			base=`echo $i | sed "s/.\$EXT$//"`
			if test x$base = xindex
			then
				title=$3
			else
				title=$3$base.html
			fi
			page "$1" "$base" "$2" "$title" > "../output/$1$base.html"
			;;
		*/)
			process "$1$i" "$2</a> <a href='$PREFIX$1$i'>$i" $3$i
			;;
		*)
			;;
		esac
	done
}

if [ -d $1 ]
then
    echo ""
else
    echo "No project directory given"
    echo "Usage: mksite <project dir> <site name>"
    exit 1
fi



#site name...
# if [ $NAME == ""]
# then
#     echo "Failed to add name input"
#     echo "Usage: mksite <project dir> <site name>"
#     exit 1
# fi

if test $1
then
        mkdir -p $1/output
        if [ -e $1/config.conf ]
        then
            source $1/config.conf
        else
            echo "WARNING: Config file not found!"
            echo "Please create config.conf in project dir"
            echo "to configure site name and footer"
        fi    
	cd $1/input
fi

rsync -av \
    --delete-excluded \
    --progress \
    --exclude=*.md \
    --exclude=*~ \
    . ../output/

echo ""
echo ""

find . -type l | xargs rm -f
process "./" "<a href='/'>$NAME/" /

